# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0OM1mODrF1YEC1teLkuTLu2x7XD0dH0
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
pca_data = pd.read_csv("/content/pca_data.csv")
logo_path = "/content/nike logo.jpg"

# Display Logo
st.image(logo_path, use_container_width=True)

# App Title
st.title("Nike Shoes Sales Analysis")

# PCA Data Section
st.header("PCA Analysis")
st.write(f"Number of components retained: {pca_data.shape[1]}")

# Show PCA Data
if st.checkbox("Show PCA Data"):
    st.dataframe(pca_data)

# Scatter Plot for PCA
st.subheader("PCA: First Two Components")
fig, ax = plt.subplots(figsize=(8, 5))
sns.scatterplot(x=pca_data["PC1"], y=pca_data["PC2"], alpha=0.6, ax=ax)
ax.set_title("PCA Projection: First Two Components")
ax.set_xlabel("Principal Component 1")
ax.set_ylabel("Principal Component 2")
st.pyplot(fig)